api_map_homepage:
    path:     /login
    defaults: { _controller: ApiMapBundle:Default:index }

api_map_signup:
    path:     /signup
    defaults: { _controller: ApiMapBundle:Default:signup }

login_login_logout:
    path:     /logout
    defaults: { _controller: ApiMapBundle:Default:logout }   
    
table_population:
    path:     /population
    defaults: { _controller: ApiMapBundle:Default:population }   


    
